seed: 7
lr: 0.05
num_classes: 250
batch_size: 32
train_base: 12
root_dir: "/mnt/f/sketchy/256x256"
num_workers: 16 #exceed -> overheat
max_epochs: 1
refresh_rate: 30
log_dir: "lightning_logs/"
exp_name: "cnn_flipped"
model_name: "CNN"
val_check_interval: 0.25
resume_path: ""
topk: 5
flip_bw: True
fps_mode: 2